In [1]:
import numpy as np 

数组切片， 索引

In [2]:
a = np.arange(10)

a[2:7:2]

array([2, 4, 6])

In [3]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
t = np.arange(24).reshape(4, 6)
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
t[1]

array([ 6,  7,  8,  9, 10, 11])

In [9]:
t[:3:2]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17]])

In [11]:
# 获取不连续的多行
t[[0, 2]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17]])

In [18]:
t[[0, 2], :-1]

array([[ 0,  1,  2,  3,  4],
       [12, 13, 14, 15, 16]])

In [26]:
t[[0, 1], [0, 2]]
t

array([[100,   0,   2,   3,   4,   5],
       [  6,   7, 100,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [28]:
t < 10

array([[False,  True,  True,  True,  True,  True],
       [ True,  True, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [32]:
t[t<10] = 1000

In [33]:
t

array([[ 100, 1000, 1000, 1000, 1000, 1000],
       [1000, 1000,  100, 1000,   10,   11],
       [  12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23]])

In [41]:
(t > 10) & (t < 50)

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [48]:
t[(t > 10) & (t < 50)] = 1

In [47]:
t = np.arange(24).reshape(4, 6)

In [49]:
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  1],
       [ 1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1]])

In [50]:
scorces = np.array([89, 81, 71, 78, 100, 90, 78, 20])

In [51]:
scorces.max()

100

In [56]:
a = scorces[scorces < scorces.max()]

In [63]:
least = scorces.min()
largest = scorces.max()

scorces[(scorces < largest) & (scorces > least)].mean()

81.16666666666667

In [66]:
np.where(scorces > 70, True, False)

array([ True,  True,  True,  True,  True,  True,  True, False])

In [68]:
a = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 1]])
a.argmax()

5

In [76]:
# 返回最大值的坐标
position = np.unravel_index(a.argmax(), a.shape)
position

(1, 2)

In [82]:
pos_tuple = np.where(a==np.max(a))
list(zip(pos_tuple[0], pos_tuple[1]))

[(1, 2)]

In [85]:
pos_tuple[0]

array([1], dtype=int64)

In [97]:
t = np.arange(24, dtype=float).reshape(4, 6)
t

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [98]:
np.nan == np.nan

False

In [99]:
type(np.nan)

float

In [101]:
t[3,4] = np.nan

In [106]:
t[:, 4]

array([ 4., 10., 16., nan])

In [109]:
np.isnan(t)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [112]:
np.count_nonzero(t != t)

1

In [111]:
t != t

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [105]:
np.sum(t[:,4])

nan

In [115]:
# 填充nan值
for i in range(t.shape[1]):
    temp_col = t[:, i]

    # 判断当前的数据是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    if nan_num:
        temp_col_not_nan = temp_col[temp_col == temp_col]

        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)


In [116]:
t

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 10., 23.]])

In [120]:
t[:, 1]

array([ 1.,  7., 13., 19.])