## Numpy 特点

- NumPy是在一个连续的内存块中存储数据，独立于其他Python内置对象。NumPy的C语言编写的算法库可以操作内存，而不必进行类型检查或其它前期工作。比起Python的内置序列，NumPy数组使用的内存更少。
- NumPy可以在整个数组上执行复杂的计算，而不需要Python的for循环。

In [1]:
import numpy as np 

my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 14.6 ms, sys: 9.46 ms, total: 24.1 ms
Wall time: 37.7 ms
CPU times: user 942 ms, sys: 201 ms, total: 1.14 s
Wall time: 2.2 s


基于Numpy的算法要比纯python快10到100倍, 并且使用的内存更少!

## Numpy 的基本使用

### 小试牛刀

In [3]:
import numpy as np

data = np.random.randn(2, 3)

data

array([[ 0.90184708,  0.84269802,  1.19988123],
       [-1.48844771, -1.80939602,  0.0022794 ]])

In [4]:
data * 10

array([[  9.01847076,   8.42698018,  11.99881231],
       [-14.88447713, -18.09396019,   0.02279401]])

In [5]:
data * data

array([[8.13328148e-01, 7.10139950e-01, 1.43971497e+00],
       [2.21547659e+00, 3.27391395e+00, 5.19566900e-06]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

### 创建ndarray

In [8]:
data1 = [1, 2., 3, 6, 7, 8]

arr1 = np.array(data1)

arr1

array([1., 2., 3., 6., 7., 8.])

列表转换为array

In [9]:
data2 = [[1, 2, 3], [4, 5, 6]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3],
       [4, 5, 6]])

多维数组的转换

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 3)

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3, 6))  # 3 行 6 列

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2, 3, 2))

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 3.16235113e+180],
        [2.31584178e+077, 2.31584178e+077]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### ndarray 的数据类型

In [18]:
arr1 = np.array([1,2,3], dtype=np.float64)

arr1.dtype

dtype('float64')

In [19]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

arr2.dtype

dtype('int32')

转换数据类型

In [20]:
arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int64')

In [21]:
float_arr = arr.astype(np.float64)

float_arr.dtype

dtype('float64')

In [22]:
arr = np.array([3.6, 1.2, -2.3, 0.4, 5.6])

arr

array([ 3.6,  1.2, -2.3,  0.4,  5.6])

In [23]:
arr.astype(np.int32)

array([ 3,  1, -2,  0,  5], dtype=int32)

### Numpy 数组运算

In [24]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [26]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [28]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [29]:
arr2 = np.array([[0., 1., 5.], [5., 1., 34.]])

arr2

array([[ 0.,  1.,  5.],
       [ 5.,  1., 34.]])

In [30]:
arr2 > arr1

array([[False, False,  True],
       [ True, False,  True]])

### 基本的索引和切片

In [31]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[5]

5

In [33]:
arr[5:8]

array([5, 6, 7])

In [34]:
arr[5:8] = 12

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
arr_slice = arr[5:8]

arr_slice

array([12, 12, 12])

In [36]:
arr_slice[:] = 10

arr_slice

array([10, 10, 10])

In [37]:
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [38]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr2d[2]

array([7, 8, 9])

In [39]:
arr2d[0][1]

2

In [40]:
arr2d[0, 1]

2

In [41]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
old_vlues = arr3d[0].copy()

old_vlues

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr3d[0] = 666

arr3d

array([[[666, 666, 666],
        [666, 666, 666]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [45]:
arr3d[0] = old_vlues

In [46]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[1, 0]

array([7, 8, 9])

In [48]:
arr3d[0, 1, 2]

6

### 切片索引

In [49]:
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [50]:
arr[1:6]

array([ 1,  2,  3,  4, 10])

In [51]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [54]:
arr2d[:2, 1:] = 0

arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 布尔型索引

In [55]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Joe'])

data = np.random.randn(6, 4)

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Joe'], dtype='<U4')

In [56]:
data

array([[-0.42161337,  0.17842404,  0.26519962,  0.5798109 ],
       [-0.06677502, -0.16824498, -0.24843702, -0.40754199],
       [ 1.00018261, -0.63407997,  1.08328946, -0.9273795 ],
       [ 1.50968663, -0.14093311, -1.31561507,  0.65194978],
       [ 0.09705215,  0.89344961, -1.56067694,  0.32131822],
       [-0.34709662, -0.3761095 ,  1.73364065,  1.09324818]])

In [57]:
names == 'Bob'

array([ True, False, False,  True, False, False])

In [58]:
data[names == 'Bob']

array([[-0.42161337,  0.17842404,  0.26519962,  0.5798109 ],
       [ 1.50968663, -0.14093311, -1.31561507,  0.65194978]])

In [59]:
data[names == 'Bob', 2:]

array([[ 0.26519962,  0.5798109 ],
       [-1.31561507,  0.65194978]])

In [60]:
data[names == 'Bob', 3]

array([0.5798109 , 0.65194978])

In [61]:
names != 'Bob'

array([False,  True,  True, False,  True,  True])

In [62]:
data[~(names != 'Bob')]

array([[-0.42161337,  0.17842404,  0.26519962,  0.5798109 ],
       [ 1.50968663, -0.14093311, -1.31561507,  0.65194978]])

In [63]:
mask = (names == 'Bob') | (names == 'Will')

mask

array([ True, False,  True,  True, False, False])

In [64]:
data[mask]

array([[-0.42161337,  0.17842404,  0.26519962,  0.5798109 ],
       [ 1.00018261, -0.63407997,  1.08328946, -0.9273795 ],
       [ 1.50968663, -0.14093311, -1.31561507,  0.65194978]])

In [65]:
data[data < 0] = 0

data

array([[0.        , 0.17842404, 0.26519962, 0.5798109 ],
       [0.        , 0.        , 0.        , 0.        ],
       [1.00018261, 0.        , 1.08328946, 0.        ],
       [1.50968663, 0.        , 0.        , 0.65194978],
       [0.09705215, 0.89344961, 0.        , 0.32131822],
       [0.        , 0.        , 1.73364065, 1.09324818]])

### 花式索引

In [66]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [67]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [68]:
arr = np.arange(32).reshape((8, 4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [69]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [70]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 数组转置和轴对称

In [71]:
arr = np.arange(15).reshape((3, 5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [73]:
arr = np.random.randn(6, 3)

arr

array([[ 1.19847852,  0.04307319,  0.23071521],
       [-1.02769034,  0.77059721, -0.59356546],
       [ 0.26186308,  0.46564627,  0.66874167],
       [ 0.5937954 , -0.62241598, -1.85025573],
       [ 1.14298452,  0.5374248 , -1.12927625],
       [ 0.36910766,  0.30759677, -0.93775047]])

In [74]:
np.dot(arr.T, arr)

array([[ 4.35631751, -0.26016065, -1.67392203],
       [-0.26016065,  1.58334466,  0.12021347],
       [-1.67392203,  0.12021347,  6.43085195]])

In [121]:
arr = np.arange(1, 25).reshape([2,3,4])

arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [122]:
arr2 = arr.transpose((1, 0, 2))

arr2

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [123]:
arr.transpose((2, 1, 0))

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [124]:
arr.transpose(2, 0, 1)

array([[[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]],

       [[ 4,  8, 12],
        [16, 20, 24]]])

transpose 是对矩阵索引的一次调整. 原先矩阵是一个三维矩阵, 索引顺序是x, y, z, 角坐标分别是0, 1, 2
![arr3d](./img/arr3d.png)

In [82]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [127]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [129]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [130]:
arr.transpose((0, 2, 1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### 通用函数: 快速的元素级数组函数

In [132]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [134]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [135]:
x = np.random.randn(8)
y = np.random.randn(8)

x

array([ 1.15173864, -0.62862117, -0.33124191,  0.14552238,  0.32622054,
        0.92615151, -0.99369172,  0.22925887])

In [136]:
y

array([-0.55465701,  1.57229153,  0.40352379, -0.29567113,  0.30272052,
        0.42358627,  0.88701548,  0.43499932])

In [138]:
np.maximum(x, y)

array([1.15173864, 1.57229153, 0.40352379, 0.14552238, 0.32622054,
       0.92615151, 0.88701548, 0.43499932])

#### 利用数组进行数据处理

In [139]:
points = np.arange(-5, 5, 0.01)

points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [141]:
xs, ys = np.meshgrid(points, points)

ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [142]:
z = np.sqrt(xs ** 2, ys ** 2)

z

array([[5.  , 4.99, 4.98, ..., 4.97, 4.98, 4.99],
       [5.  , 4.99, 4.98, ..., 4.97, 4.98, 4.99],
       [5.  , 4.99, 4.98, ..., 4.97, 4.98, 4.99],
       ...,
       [5.  , 4.99, 4.98, ..., 4.97, 4.98, 4.99],
       [5.  , 4.99, 4.98, ..., 4.97, 4.98, 4.99],
       [5.  , 4.99, 4.98, ..., 4.97, 4.98, 4.99]])

In [150]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, False, False])

result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

result

[1.1, 2.2, 1.3, 2.4, 2.5]

In [151]:
result = np.where(cond, xarr, yarr)

result

array([1.1, 2.2, 1.3, 2.4, 2.5])

In [152]:
arr = np.random.randn(4, 4)

arr

array([[-0.29625638,  0.38523622,  0.13305278,  1.11435554],
       [ 0.46493789, -1.08080402,  0.2522638 , -1.50532709],
       [-0.01466075,  0.05446288,  0.14770636,  0.46231237],
       [-0.13312418, -0.42628395, -0.1371267 ,  1.28843969]])

In [153]:
arr > 0

array([[False,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True,  True],
       [False, False, False,  True]])

In [157]:
np.where(arr > 0, 2, arr)

array([[-0.29625638,  2.        ,  2.        ,  2.        ],
       [ 2.        , -1.08080402,  2.        , -1.50532709],
       [-0.01466075,  2.        ,  2.        ,  2.        ],
       [-0.13312418, -0.42628395, -0.1371267 ,  2.        ]])

### 数学和统计方法

In [158]:
arr = np.random.randn(5, 4)

arr

array([[ 1.49769479, -0.24353395, -0.72442839, -0.72429049],
       [ 0.0191613 ,  0.72187837, -1.0790642 , -0.57226631],
       [-1.42869537,  0.48181489, -0.43792619,  0.18285091],
       [ 1.15946371,  0.74923296,  0.28343124,  0.59668244],
       [ 0.53005561, -1.8564091 , -0.5897144 ,  0.18112743]])

In [159]:
arr.mean()

-0.0626467380814206

In [160]:
arr.sum()

-1.252934761628412

In [166]:
arr.mean(axis=0)

array([ 0.35553601, -0.02940337, -0.50954039, -0.0671792 ])

In [168]:
arr.sum(axis=1)

array([-0.19455803, -0.91029086, -1.20195575,  2.78881035, -1.73494047])

In [171]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [179]:
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [181]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [182]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [191]:
arr = np.random.randn(100)

(arr > 0).sum()

44

In [192]:
bools = np.array([False, False, True, False])

bools.any()

True

In [193]:
bools.all()

False

### 排序

In [199]:
arr = np.random.randn(5, 3)

arr

array([[-0.44894941, -1.28355592, -0.59350271],
       [-0.7978722 , -0.62398854, -0.64211603],
       [ 0.73321291, -0.07345042, -0.42409661],
       [-0.79928229,  0.00552293,  1.27205778],
       [-0.49118562,  0.11289211, -0.60722497]])

In [200]:
arr.sort(1)

arr

array([[-1.28355592, -0.59350271, -0.44894941],
       [-0.7978722 , -0.64211603, -0.62398854],
       [-0.42409661, -0.07345042,  0.73321291],
       [-0.79928229,  0.00552293,  1.27205778],
       [-0.60722497, -0.49118562,  0.11289211]])

In [203]:
arr.sort()

arr

array([[-1.28355592, -0.59350271, -0.44894941],
       [-0.7978722 , -0.64211603, -0.62398854],
       [-0.42409661, -0.07345042,  0.73321291],
       [-0.79928229,  0.00552293,  1.27205778],
       [-0.60722497, -0.49118562,  0.11289211]])

### 唯一化以及其它的集合逻辑

In [204]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [205]:
values = np.array([6, 0, 3, 2, 5, 6])

np.in1d(values, [2, 3, 6])

array([ True, False,  True,  True, False,  True])

### 线性代数

In [206]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8., 9.]])

x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [207]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [208]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [210]:
x.dot(np.ones(3))

array([ 6., 15.])

In [211]:
x @ np.ones(3)

array([ 6., 15.])

In [212]:
x = np.random.randn(5, 5)

x

array([[ 0.07840579, -1.66011271,  0.89333324,  0.04830275, -0.69277549],
       [-1.47004149, -1.77877454, -0.78563048,  0.90440154,  0.11064465],
       [ 0.22013487, -0.4020207 ,  1.92982327, -0.53525075,  0.55389087],
       [ 1.22562533,  0.14092196,  0.29745007,  1.00696995, -0.20627248],
       [-1.18012031, -0.35096492, -0.84582786, -0.13275207, -0.38317838]])

In [213]:
mat = x.T.dot(x)

mat

array([[ 5.11047021,  2.98310951,  3.01251428, -0.05271663,  0.10434468],
       [ 2.98310951,  6.22466906, -0.52263009, -1.28523706,  0.83601177],
       [ 3.01251428, -0.52263009,  5.94337869, -1.28850564,  0.62585351],
       [-0.05271663, -1.28523706, -1.28850564,  2.13838026, -0.38670875],
       [ 0.10434468,  0.83601177,  0.62585351, -0.38670875,  0.98834922]])

In [215]:
np.linalg.inv(mat)

array([[ 4.876181  , -4.05722279, -4.13024684, -4.09639006,  3.92968593],
       [-4.05722279,  3.59454799,  3.5046214 ,  3.54961225, -3.44255674],
       [-4.13024684,  3.5046214 ,  3.7196363 ,  3.61874206, -3.46788723],
       [-4.09639006,  3.54961225,  3.61874206,  4.09090046, -3.26088839],
       [ 3.92968593, -3.44255674, -3.46788723, -3.26088839,  4.42895216]])